export default {
  email_placeholder: 'Email',
  password_placeholder: 'Senha',
  login_button: 'Login',
  register_link: 'Cadastro',
  forgot_password_link: 'Esqueceu sua senha?',
  forgot_password_confirm: 'Tem certeza que desenha redefinir sua senha?',
  facebook_login_button: 'Login com Facebook.',
  password_blank_messege: 'A senha não pode ficar em branco.',
  password_alphaNumeric_check:
    'A senha deve conter ao menos um caractere alfanumérico. O tamanho deve ser entre 8 e 15 caracteres.',
  password_complexity_check:
    'Sua senha deve conter no mínimo 1 letra maiúscula , 1 letra minúscula, 1 número e 1 caractere especial. O tamanho deve ser entre 6 e 10 caracteres.',
  valid_email_check: 'Favor inserir um email válido.',
  email_not_found: 'Email não encontrado na base de dados.',
  valid_rider: 'Insira uma conta de usuário válida.',
  facebook_login_error: 'Erro no login. ',
  apple_signin_error:
    'A autenticação via Apple não foi habilitada, por isso utilizamos seu email para autenticação comum (email, senha).',
  forgot_password_success_messege:
    'Um link de redefinção de senha foi enviada ao seu email.',
  facebook_login_auth_error: 'Erro no login com o Facebook:',
  google_login_auth_error: 'Erro no login com o Google:',
  static_notification_title: 'Notificação GrabCab',
  modal_closed: 'A janela foi fechada.',
  refferal_code_validation_modal: 'Validando seu código de indicação...',
  refferal_id_not_match_error: 'Código de indicação inválido.',
  registration_title: 'Cadastro',
  first_name_placeholder: 'Nome',
  first_name_blank_error: 'Favor inserir seu nome.',
  last_name_placeholder: 'Sobrenome',
  last_name_blank_error: 'Favor inserir seu sobrenome.',
  login_title: 'Login c/ Telefone',
  mobile_no_placeholder: 'Celular',
  mobile_no_blank_error: 'Favor inserir um número de telefone válido.',
  otp_error: 'Insira o OTP correto',
  otp_here: 'Favor digitar o OTP',
  sending_otp: 'Enviando o OTP...',
  authorize: 'Autorizar',
  request_otp: 'Solicitar OTP',
  firebase_otp_error:
    'Erro ao autenticar com o OTP. Verifique o seu número. Adicione o código do país na frente.',
  spacer_message: 'OU CONECTAR COM',
  confrim_password_placeholder: 'Confirme a senha',
  confrim_password_not_match_err: 'As senhas não coincidem',
  referral_id_placeholder: 'Código de Indicação (Opcional)',
  register_button: 'Cadastrar',
  email_exist_error: 'Já existe um cadastro com este email.',
  Account_linking_error: 'Erro ao conectar com esta conta',
  send_email_button: 'Enviar email',
  book_your_ride_menu: 'Solicitar',
  profile_setting_menu: 'Perfil',
  my_wallet_menu: 'Minha carteira',
  my_rides_menu: 'Histórico',
  logout: 'Sair',
  about_us_menu: 'Sobre nós',
  image_size_warning: '(Tamanho máximo: 2 MB)',
  upload_driving_lisence:
    'Envie uma foto com seu rosto que servirá para autenticação',
  photo_upload_action_sheet_title: 'Escolha o tipo do arquivo: ',
  camera: 'Câmera',
  galery: 'Galeria',
  cancel: 'Cancelar',
  yes: 'Sim',
  network_request_failed: 'Erro na rede',
  password_update_messege: 'Senha atualizada com sucesso!',
  delete_account_modal_title: 'Confirmação',
  delete_account_modal_subtitle: 'Deseja apagar sua conta ?',
  profile_page_title: 'Meu perfil',
  my_wallet_title: 'Saldo da carteira',
  profile_page_subtitle: 'Detalhes do perfil',
  location_lebel: 'Localização',
  language_lebel: 'Idioma',
  preffer_language: 'Português',
  change_password_lebel: 'Alterar senha',
  delete_account_lebel: 'Apagar conta',
  change_password_modal_title: 'Trocar a senha?',
  old_password_placeholder: 'Antiga senha',
  new_password_placeholder: 'Nova senha',
  old_password_validation_error: 'Favor preencher a senha antiga',
  new_password_validation_error: 'Favor preencher a senha nova',
  update_button: 'Atualizar',
  update_profile_title: 'Atualizar perfil',
  map_screen_where_input_text: 'Onde embarcar ?',
  map_screen_drop_input_text: 'Onde descer?',
  map_screen_drop_input_add: 'Ponto de Parada',
  driver_finding_alert: 'Encontrando prestadores...',
  no_driver_found_alert_title: 'Alerta!',
  no_driver_found_alert_messege:
    'Desculpa, Nenhum prestador foi encontrado. Tente novamente mais tarde.',
  no_driver_found_alert_OK_button: 'OK',
  no_driver_found_alert_TRY_AGAIN_button: 'Tenten novamente',
  pickup_and_drop_location_blank_error:
    'Selecione o local de embarque e o local de destino.',
  pickup_location_blank_error: 'Selecione o local de embarque.',
  drop_location_blank_error: 'Selecione o local de destino',
  car_type_blank_error: 'Selecione o tipo de serviço',
  congratulation: 'Parabéns!',
  refferal_bonus_message_text: 'Seu saldo-bônus por indicações -',
  map_screen_title: 'Embarcar',
  where_we_going: 'Pra onde vamos?',
  cab_selection_title: 'Escolha o serviço',
  cab_selection_subtitle: 'Clique para escolher um serviço.',
  not_available: 'Não disponível',
  // book_now_button:'Para agora',
  book_now_button: 'Ir agora',
  contact_details: 'Detalhes de contato',
  phone: 'Telefone',
  my_wallet_tile: 'Minha carteira',
  wallet_ballance: 'Saldo',
  add_money: 'Adicionar dinheiro',
  transaction_history_title: 'Histórico de Transações',
  successfully: 'Successo',
  form_wallet: 'Carteira',
  Transaction_Id: 'ID da transação: ',
  ride_list_title: 'Minhas corridas',
  no_car_assign_text: 'Nenhum prestador atribuído',
  not_found_text: 'Não encontrado',
  ride_details_page_title: 'Detalhes da corrida',
  you_rated_text: 'Você recebeu uma avaliação',
  car_no_not_found: 'Placa do veículo não encontrado',
  track_now_button: 'Localizar agora',
  bill_details_title: 'Detalhes da conta',
  your_trip: 'Sua viagem',
  discount: 'Desconto',
  promo_apply: '(Aplicar cupom-desconto)',
  grand_total: 'Total geral',
  payment_status: 'Status do pagamento',
  paynow_button: 'Pagar agora',
  call_driver: 'Ligar para o prestador',
  booked_cab_title: 'Serviço agendado',
  you_selected: ' Você selecionou  -',
  otp: 'OTP :',
  driver_assign_messege: 'O prestador chegará em breve...',
  cancel_ride: 'Cancelar solicitação',
  rider_cancel_text: 'Cancelar solicitação',
  submit_rating: 'ENVIAR AVALIAÇÃO',
  cancel_messege1: 'Sua solicitação de ID ',
  cancel_messege2: 'foi cancelada com sucesso!',
  dont_cancel_text: 'Não cancelar',
  cancel_reason_modal_title: 'Motivo do cancelamento',
  chat_title: 'Chat',
  send_button_text: 'Enviar',
  chat_input_title: 'Digite algo...',
  chat_not_found: 'Não há conversas por aqui',
  card_payment_blank_error: 'Favor preencher todos os detalhes corretamente.',
  payment_amound_error: 'O valor de pagamento é muito baixo.',
  invalid_card_details_error: 'Cartão inválido.',
  success_payment: 'Pagamento concluído com sucesso',
  confrimation: 'Confirmação',
  payment_alert: 'Deseja apagar este cartão ?',
  please_wait: 'Por favor aguarde...',
  enterCVV: 'Insira o CVV',
  your_promo: 'Promoções',
  promo_exp: 'Desculpa! Esta promoção expirou.',
  promo_limit: 'Desculpa! Promoção excedeu o limite de uso.',
  promo_eligiblity: 'Desculpa! Perfil não elegível a esta promoção.',
  payment: 'Pagamento',
  bill_details: 'Detalhes da fatura',
  apply_promo: 'Aplicar cupom',
  apply: 'APLICAR',
  driver_near: 'Prestador perto de você',
  your_fare: 'Sua tarifa',
  promo_discount: 'Desconto promocional',
  wallet_discount: 'Desconto na carteira',
  payable_ammount: 'Valor a pagar',
  use_wallet_balance: 'Usar saldo da carteira (Saldo atual) ',
  pay_cash: 'Pagar em dinheiro',
  pay_card: 'Pagar com cartão',
  proceed_pay: 'Prosseguir com o pagamento',
  save_card: 'Cartões salvos',
  thanks: 'Obrigado pela avaliação',
  skip: 'Pular',
  receipt: 'Receita',
  rate_ride: 'AVALIE A CORRIDA',
  err: 'Erro!',
  route_not_found: 'Não encontramos nenhuma rota',
  sorry: 'Desculpa',
  multipleBooking:
    'Atualmente não é possível fazer várias corridas simultâneamente.',
  driver_not_found:
    'Não foi possível atribuir um prestador no momento. Contate o administrador !!!',
  new_booking_request_push_notification: 'Novo serviço, ',
  fare_details: 'Detalhamento da tarifa',
  base_fare: 'Taxa base',
  convenience_free: 'Taxa de convienência',
  total_fare: 'Total',
  inclusive_tax: '(Todas as taxas incluídas)',
  nb:
    'Atenção: Sua tarifa aumentará se o pedágio, a rota e o destino mudarem ou ainda se a viagem demorar mais devido ao trânsito. ',
  confirm_booking: 'Confirmar solicitação',
  estimate_fare_text: 'Tarifa estimada',
  suggested_price: 'Preço sugerido',
  done: 'Pronto',
  notification_headerText: 'Notificação',
  notification_not_found: 'Nenhuma notificação encontrada',
  track_cab: 'Localizar prestador',
  location_permission: 'Permissão para acessar localização',
  ask_me_later: 'Perguntar depois',
  min_order_value: 'Valor mínimo do pedido -',
  add_money_tile: 'Adicionar dinheiro',
  addMoneyTextInputPlaceholder: 'Adicionar saldo',
  transactionFaildMsg: 'Erro na transação',
  payWithCard: 'Pagar com cartão',
  CardPaymentAmount: 'Pagar com o cartão',
  CashPaymentAmount: 'Pagar em dinheiro',
  WalletPayment: 'Pagar com o saldo da carteira',
  pay_mode: 'Modo de pagamento',
  Balance: 'Saldo do GrabCab',
  android_channel: 'Notificações do GrabCab',
  write_message: 'Escreva a sua mensagem',
  terms: 'Termos & Condições',
  panic_text: 'Botão do Pânico',
  panic_question: 'Deseja acionar o botão do pânico?',
  email_login: 'Login com Email',
  register_email: 'Cadastro com Email',
  ok: 'OK',
  book_later_button: 'Agendar',
  past_booking_error:
    'Não é possível agendar um serviço para uma data passada ou para os próximos 15 minutos.',
  alert: 'Alerta',
  booking_taken:
    'Agendamento realizado. Um prestador será acionado 15 minutos antes da hora marcada. ID da solicitação: ',
  select_country: 'Selecione o País',
  country_blank_error: 'Favor selecionar o país',
  email_verify_message:
    'Favor verificar sua caixa de mensagens. O Email foi enviado com sucesso!',
  downloading_updates: 'Baixando atualizações...',
  checking_updates: 'Verificando atualizações...',
  fetching_data: 'Atualizando os dados...',
  loading_assets: 'Carregando os arquivos...',
  form_of_payment: 'Forma de pagamento',
  duration_booking: 'A duração da viagem',
  will_be: 'será de',
  minutes: 'minuto(s)',
  money: 'dinheiro',
  card: 'cartão',
  loading_assets: 'Carregando os arquivos...',
  payment_method_title: 'Meus cartões',
  has_sent_message_to_you: 'enviou uma mensagem para você',
  has_cancelled_current_booking: 'cancelou a reserva atual'
}
